#!/bin/sh

GIT_COLOR="#88C0D0"

git_color_text() {
	gum style --foreground "$GIT_COLOR" "$1"
}

get_branches() {
	if [ ${1+x} ]; then
		gum choose --selected.foreground="$GIT_COLOR" --limit="$1" $(git branch --format="%(refname:short)")
	else
		gum choose --selected.foreground="$GIT_COLOR" --no-limit $(git branch --format="%(refname:short)")
	fi
}

git rev-parse --git-dir >/dev/null 2>&1

if [ $? -ne 0 ]; then
	echo "$(git_color_text "!!") Must be run in a $(git_color_text "git") repo"
	exit 1
fi

gum style \
	--border normal \
	--margin "1" \
	--padding "1" \
	--border-foreground "$GIT_COLOR" \
	"$(git_color_text ' Git') Branch Manager"

TYPE=$(gum choose "fix" "feat" "docs" "style" "refactor" "test" "chore" "revert")
SCOPE=$(gum input --placeholder "scope")

test -n "$SCOPE" && SCOPE="($SCOPE)"

SUMMARY=$(gum input --value "$TYPE$SCOPE: " --placeholder "Summary of this change")
DESCRIPTION=$(gum write --placeholder "Details of this change (CTRL+D to finish)")
gum confirm --default=false "Add footer?" && FOOTER=$(gum write --placeholder "Footer (CTRL+D to finish)")
if [ -z ${FOOTER+x} ]; then
	gum confirm "Commit changes?" && git commit -m "$SUMMARY" -m "$DESCRIPTION"
else
	gum confirm "Commit changes?" && git commit -m "$SUMMARY" -m "$DESCRIPTION" -m "$FOOTER"
fi
