#!/bin/bash

set -e

# Exporting the specific shell we want to work with:

SHELL=$(which zsh)
export SHELL

# Standard dotbot pre-configuration:

readonly DOTBOT_DIR='dotbot'
readonly DOTBOT_BIN='bin/dotbot'
readonly BASEDIR="$(cd "$(dirname "${(%):-%x}")" && pwd)"

readonly ARGS="$@"

cd "$BASEDIR"
git submodule sync --quiet --recursive
git submodule update --init --recursive

# Linking dotfiles:

run_dotbot () {
  local config
  config="$1"

  "$BASEDIR/$DOTBOT_DIR/$DOTBOT_BIN" \
    -d "$BASEDIR" \
    --plugin-dir dotbot-brewfile \
    --plugin-dir dotbot-pip \
    -c "$config" $ARGS
}

run_dotbot 'steps/terminal.yml' || true
run_dotbot 'steps/dependencies.yml' || true
run_dotbot 'steps/vscode.yml' || true
